services:
  api:
    build: ..
    image: clemoudo/shot-n-go:api-dev-latest
    volumes:
      - ./KEY/firebase-key.json:/code/KEY/firebase-key.json
      - ../images:/images
    networks:
      - redis_net
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8000:5000/tcp"

  redis:
    image: redis:alpine
    networks:
      - redis_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  redis_net:
