services:
  proxy:
    image: clemoudo/shot-n-go:proxy-latest
    networks:
      - proxy_net
      - react_net
      - api_net

  api:
    image: clemoudo/shot-n-go:api-latest
    volumes:
      - ./api/KEY/firebase-key.json:/code/app/KEY/firebase-key.json
    networks:
      - api_net

  react:
    image: clemoudo/shot-n-go:react-latest
    networks:
      - react_net

networks:
  proxy_net:
    external: true
  react_net:
  api_net:
