services:
  proxy:
    build: ./proxy
    image: clemoudo/shot-n-go:proxy-latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - dmz_net
    depends_on:
      - api
      - react
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./proxy/letsencrypt/fullchain.pem:/etc/letsencrypt/live/m1-1.ephec-ti.be/fullchain.pem
      - ./proxy/letsencrypt/privkey.pem:/etc/letsencrypt/live/m1-1.ephec-ti.be/privkey.pem

  api:
    build: ./api
    image: clemoudo/shot-n-go:api-latest
    volumes:
      - ./api/KEY/firebase-key.json:/code/KEY/firebase-key.json
      - api_images:/images
    networks:
      - dmz_net
      - redis_net
      - db_net
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mariadb 
      - DB_PORT=3306
      - DB_NAME=shotngo
      - DB_USER=shotuser
      - DB_PASSWORD=shotpass
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  react:
    build: ./react
    image: clemoudo/shot-n-go:react-latest
    networks:
      - dmz_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    image: redis:alpine
    networks:
      - redis_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shotngo
      MYSQL_USER: shotuser
      MYSQL_PASSWORD: shotpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_net

networks:
  dmz_net:
  redis_net:
  db_net:

volumes:
  mariadb_data:
  api_images:
