name: Build and push images on PUSH to main

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Rendre le script exécutable
        run: chmod +x docker/build_push.sh

      - name: Installer les dépendances
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Exécuter le script
        run: ./docker/build_push.sh
